version: '3.8'

services:
  app:
    build: .
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:quoteDB;DB_CLOSE_DELAY=-1
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=sa
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_H2_CONSOLE_PATH=/h2-console
    volumes:
      - h2-data:/app/data
    networks:
      - app-network

volumes:
  h2-data:

networks:
  app-network:
